tildes into $HOME. get rid of nohup etc.

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -6,21 +6,13 @@ function switch(){
     echo "Server $arg is not defined."
     exit 0
   fi
-
-  if [ -d ~/$arg ]; then
-    [[ "$PWD" == $HOME/$arg* ]] && cd ~
-    fusermount -z -u ~/$arg 2>/dev/null || echo "$arg is not mounted"
-    rmdir ~/$arg || echo "~/$arg cannot be deleted"
-    # if [ ${settings[4]} -gt 0 ]; then
-    #   tmp=$(netstat -atnp 2>/dev/null|grep '127.0.0.1:'${settings[4]} |grep '0.0.0.0'|tr -s ' '|cut -d " " -f 7)
-    #   kill ${tmp/\/ssh/}
-    # fi
+  if [ -d $HOME/$arg ]; then
+    [[ "$PWD" == $HOME/$arg* ]] && cd $HOME
+    fusermount -z -u $HOME/$arg 2>/dev/null || echo "$arg is not mounted"
+    rmdir $HOME/$arg || echo "$HOME/$arg cannot be deleted"
   else
-    # if [ ${settings[4]} -gt 0 ]; then
-    #   ssh -L ${settings[4]}:${settings[5]}:22 ${settings[6]} -fq "sleep 1" 
-    # fi
-    mkdir -p ~/$arg
-    nohup &>/dev/null sshfs ${settings[1]}:${settings[3]} ~/$arg -o transform_symlinks,follow_symlinks,workaround=rename,idmap=user,ssh_command="ssh -S none"||server $arg
+    mkdir -p $HOME/$arg
+    sshfs $1:. $HOME/$arg -o transform_symlinks,follow_symlinks,workaround=rename,idmap=user,ssh_command="ssh -S none"||server $arg
     # ,ssh_command="ssh -S none",no_readahead,cache=no
   fi
 }
@@ -29,4 +21,4 @@ while [[ $# -gt 0 ]]; do
  switch $1
  shift
 done
-ls --color=auto ~
+ls --color=auto $HOME
